// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa7h2mLDTBx4e-wmz7vsvZabJk99FXtYQ',
    appId: '1:576474187925:web:7fe78c7f4618f4ecd7739c',
    messagingSenderId: '576474187925',
    projectId: 'quranic-verse',
    authDomain: 'quranic-verse.firebaseapp.com',
    storageBucket: 'quranic-verse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxI0l72j2cIx-5LNSdbWMQt52nbNVBge8',
    appId: '1:576474187925:android:b59530a38f576a22d7739c',
    messagingSenderId: '576474187925',
    projectId: 'quranic-verse',
    storageBucket: 'quranic-verse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJsKUy8auGAVJ5A6MXFUYpDqTz61uIXqw',
    appId: '1:576474187925:ios:a9e8f6fe2f4c03f6d7739c',
    messagingSenderId: '576474187925',
    projectId: 'quranic-verse',
    storageBucket: 'quranic-verse.appspot.com',
    iosClientId: '576474187925-e8vvio4s57k7foj8nsm41krtqmdpnim5.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranicVerses',
  );
}
